### ISSUE TITLE
Error when "php exakat analyze -p sculpin -T All"

### ISSUE THREAD

**Issue by cyw3** [exakat/exakat#37] opened 2017-11-21 08:24 UTC
I install exakat by git.
When I use the command below:
`

php exakat init -p sculpin -R https://github.com/sculpin/sculpin.git

php exakat project -p sculpin

php exakat analyze -p sculpin -T All

`

i occur a problem:
![image](https://user-images.githubusercontent.com/11549103/33061817-09ee171c-ce63-11e7-8649-a541f537bb4e.png)

![image](https://user-images.githubusercontent.com/11549103/33061830-109a0594-ce63-11e7-973d-5bd3875b47fa.png)

**Comment by exakat** [comment] 2017-12-04 09:43
I ran sculpin on last week version, and I couldn't reproduce. 

Can you update exakat version ? Today's (upcoming) 1.0.6 version will be the best.

**Comment by exakat** [comment] 2018-01-24 08:59
We are now version 1.1.1. This error was fixed in recent versions. Please, try the newer exakat, and report it again if it still happens.

**Closed by exakat** 2018-01-24 08:59 UTC
